### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by winston-yallow** [winston-yallow/primitives#1]
- [x] basic obstructions
- [x] smooth following camera
- [x] smooth player controls for keyboard and controller
- [ ] colors
- [x] interactive obstructions
    - [x] hideouts
    - [x] teleporters
- [x] dots that the player must eat & player health
- [x] pathfinding
- [ ] enemy avoidance
- [ ] enemy states
    - [x] idle
    - [x] follow
    - [ ] search
    - [x] return
- [ ] level editor or blender export/import workflow
